M48
; DRILL file {KiCad 9.0.6-rc2} date 2025-10-26T22:09:17+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-26T22:09:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-rc2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X123.0Y-125.9
X123.1Y-50.3
T2
X187.05Y-51.05
X199.75Y-51.05
M30
